DROP TABLE IF EXISTS meters;

CREATE TABLE meters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS meter_data;

CREATE TABLE meter_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    meter_id INTEGER NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    value INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY(meter_id) REFERENCES meters(id)
);